name: Build Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload built plugin
        uses: actions/upload-artifact@v3
        with:
          name: BetterAutomatedSortingSystem
          path: target/BetterAutomatedSortingSystem-*.jar
          if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: BetterAutomatedSortingSystem

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: BetterAutomatedSortingSystem-*.jar